### PR TITLE
Cleanup json file

### PR DESCRIPTION
**Pull request by NyakudyaA**
* Removed layer configurations from a group if it is none existent in GeoServer
* Standardised names - fix errors when importing data. 
* Fix friendly layer names and groups

### CODE REVIEW

**Comment by NyakudyaA** [comment]
@dimasciput I am not sure why the test is failing here.

**Comment by timlinux** [comment]
@Christiaanvdm please review this

**Comment by dimasciput** [comment]
> @dimasciput I am not sure why the test is failing here.

@NyakudyaA the failing test is not related with this PR, we should create another PR to fix it. 

@Christiaanvdm please try to import this json with this command : `make import-data`, and fetch geocontext data with `/api/v1/geocontext/value/collection/23.1/-33.35/rainfall_group`.

**Comment by dimasciput** [comment]
@NyakudyaA can you make groups for ledet and healthyriver ?

**Review by dimasciput — APPROVED** [review]
Please do squash and merge

**Pull request merged**
