### PR TITLE
 Fix Django version inconsistencies

### LINKED ISSUE #110: Django version inconstancies causing build to fail
Make migrate fails with import errors relating to Django v3/2 compatibility.
Requirements.txt installs Django>=2.0.2 so upgrades to new major version.
Need to limit Django version to less than 3

### PR DESCRIPTION
**Pull request by andretheronsa**
Closes #110

### CODE REVIEW

**Review by dimasciput — APPROVED** [review]

**Comment by dimasciput** [comment]
Thanks @andretheronsa

**Comment by andretheronsa** [comment]
@dimasciput @NyakudyaA 
Actually, Django 2.2 [drops](https://docs.djangoproject.com/en/2.2/releases/2.2/#id1) support for GDAL 1.9 which seems to be the cause of the recent failed builds. Pinning Django to 2.1.8 seems to work and the build passes. I assume Geocontext was developed on Django < 2.2 ?

* Note.2.2 is the long term security release.

**Comment by dimasciput** [comment]
@andretheronsa yes it was developed on Django version 2.1.8, if you could modernize it to using the latest Django and python that would be better.

**Comment by andretheronsa** [comment]
> @andretheronsa yes it was developed on Django version 2.1.8, if you could modernize it to using the latest Django and python that would be better.

@dimasciput That is probably the best way to go about this, rather than trying to patch everywhere. I will close this PR and create a new issue.

**Pull request closed without merging**
